pair_device:
  description: "Pair with the RYSE BLE device"
  fields:
    address:
      description: "Bluetooth Address of the device"
      example: "AA:BB:CC:DD:EE:FF"

unpair_device:
  description: "Unpair the RYSE BLE device"

read_info:
  description: "Read data from the RYSE BLE device"

send_raw_data:
  description: "Send raw data to the RYSE BLE device"
  fields:
    data:
      description: "Data to send in hex format"
      example: "01020304"

scan_and_pair:
  description: "Scan for BLE devices and pair with the first available device"
